### ISSUE TITLE
no such Facebook group

### ISSUE THREAD

**Issue by procursor** [rrsilaya/recs2spotify#6]
## Steps to reproduce: (as per [README.md](https://github.com/rrsilaya/recs2spotify/blob/master/README.md))

1. Install the extension via any of the providers above.
2. Go to music recs without context Facebook group.

## Expected:

music recs without context Facebook group gets displayed in my lovely browser

## Actual result:

https://www.facebook.com/groups/1664811250303043/ says:

> This Content Isn't Available Right Now
> 
> When this happens, it's usually because the owner only shared it with a small group of people, changed who can see it or it's been deleted.

**Comment by rrsilaya** [comment]
Hi, as of November 9, 2020, music recs without context Facebook group has been archived. No news yet regarding when it will open again for new members.

**Comment by procursor** [comment]
I have some great ideas about missing Opera plugins and no time to
implement them. Are you interested?
